apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: smart-commerce
data:
  PORT: "4006"
  DATABASE_URL: "mongodb://mongodb:27017/smart-commerce-auth"
  MONGO_URI: "mongodb://mongodb:27017/smart-commerce-auth"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
