services:
  mongodb:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
  auth-service:
    build: ./services/auth-service
    ports: ["4006:4006"]
  user-service:
    build: ./services/user-service
    ports: ["4001:4001"]
    environment:
      DATABASE_URL: mongodb://mongodb:27017/smart-commerce-users
    depends_on:
      mongodb:
        condition: service_healthy
  product-service:
    build: ./services/product-service
    ports: ["4002:4002"]
  order-service:
    build: ./services/order-service
    ports: ["4003:4003"]
  payment-service:
    build: ./services/payment-service
    ports: ["4004:4004"]
  notification-service:
    build: ./services/notification-service
    ports: ["4005:4005"]
  api-gateway:
    build: ./api-gateway
    ports: ["8081:8080"]
    environment:
      AUTH_SERVICE_URL: http://auth-service:4006
      USER_SERVICE_URL: http://user-service:4001
      PRODUCT_SERVICE_URL: http://product-service:4002
      ORDER_SERVICE_URL: http://order-service:4003
      PAYMENT_SERVICE_URL: http://payment-service:4004
      NOTIFICATION_SERVICE_URL: http://notification-service:4005
    depends_on:
      - auth-service
      - user-service
      - product-service
      - order-service
      - payment-service
      - notification-service
  frontend:
    build: ../frontend
    ports: ["5173:80"]
    depends_on: [api-gateway]
volumes:
  mongo-data:
