FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5672
ENTRYPOINT ["node", "index.js"]


# docker build -t curly-carnival/messaging .
# docker run -d --name messaging -e RABBITMQ_URL=amqp://guest:guest@host.docker.internal:5672 messaging
